name: Generate Hexo Blog
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setup hexo environment
        run: |
          npm install -g hexo-cli
          npm ci
      - name: Generate pages
        run: |
          hexo generate
          ls -R public/